[mongodb]
mongodb.shivv-aws.fun

[redis]
redis.shivv-aws.fun

[mysql]
mysql.shivv-aws.fun

[rabbitmq]
rabbitmq.shivv-aws.fun

[catalogue]
catalogue.shivv-aws.fun

[cart]
cart.shivv-aws.fun

[user]
user.shivv-aws.fun

[payment]
payment.shivv-aws.fun

[shipping]
shipping.shivv-aws.fun

[frontend]
frontend.shivv-aws.fun

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
; [local:vars]
; COURSE=ANSIBLE
; DURATION=10HRS
; TRAINER=SIVA KUMAR